In [1]:
import pandas as pd
import numpy as np

In [2]:
df_raw = pd.read_csv("data/raw/raw_game_state_data.csv")
df = df_raw.copy()

In [3]:
df

,season,team,game_state,minutes,shots,goals,xG,shots_against,goals_against,xGA
0,2021,Arsenal,Goal diff 0,1472,225,30,26.489456,150,16,13.169800
1,2021,Arsenal,Goal diff +1,810,145,17,17.046285,100,8,7.393413
2,2021,Arsenal,Goal diff > +1,576,93,10,11.936612,71,8,9.277482
3,2021,Arsenal,Goal diff -1,368,82,3,6.066514,47,9,7.577670
4,2021,Arsenal,Goal diff < -1,353,42,1,4.009005,58,7,12.143918
...,...,...,...,...,...,...,...,...,...,...
143,2025,Tottenham,Goal diff 0,1766,189,20,20.368882,206,29,25.097431
144,2025,Tottenham,Goal diff -1,848,114,12,12.007545,124,12,16.254450
145,2025,Tottenham,Goal diff +1,449,46,6,6.156299,66,10,6.495562
146,2025,Tottenham,Goal diff < -1,343,52,7,5.915664,43,5,5.390593
147,2025,Tottenham,Goal diff > +1,273,35,3,4.486533,26,1,2.888300

In [4]:
df["goals_minus_xG"] = df["goals"] - df["xG"]
df["goals_against_minus_xGA"] = df["goals_against"] - df["xGA"]

In [5]:
df.head()

,season,team,game_state,minutes,shots,goals,xG,shots_against,goals_against,xGA,goals_minus_xG,goals_against_minus_xGA
0,2021,Arsenal,Goal diff 0,1472,225,30,26.489456,150,16,13.169800,3.510544,2.830200
1,2021,Arsenal,Goal diff +1,810,145,17,17.046285,100,8,7.393413,-0.046285,0.606587
2,2021,Arsenal,Goal diff > +1,576,93,10,11.936612,71,8,9.277482,-1.936612,-1.277482
3,2021,Arsenal,Goal diff -1,368,82,3,6.066514,47,9,7.577670,-3.066514,1.422330
4,2021,Arsenal,Goal diff < -1,353,42,1,4.009005,58,7,12.143918,-3.009005,-5.143918

In [6]:
df["minutes"] / df["goals_against"]

0       92.000000
1      101.250000
2       72.000000
3       40.888889
4       50.428571
          ...
143     60.896552
144     70.666667
145     44.900000
146     68.600000
147    273.000000
Length: 148, dtype: float64

In [7]:
df["total_goals"] = df.groupby(["season","team"])["goals"].transform("sum")
df["total_goals_against"] = df.groupby(["season", "team"])["goals_against"].transform("sum")

In [8]:
df["total_game_time"] = df.groupby(["season", "team"])["minutes"].transform("sum")

In [9]:
df["game_state_percentage"] = df["minutes"] / df["total_game_time"] *100

In [10]:
df["goals_percentage"] = df["goals"] / df["total_goals"] *100
df["goals_against_percentage"] = df["goals_against"] / df["total_goals_against"] *100

In [11]:
df["total_xG"] = df.groupby(["season", "team"])["xG"].transform("sum")
df["total_xGA"] = df.groupby(["season", "team"])["xGA"].transform("sum")

df["xG_percentage"] = df["xG"] / df["total_xG"] *100
df["xGA_percentage"] = df["xGA"] / df["total_xGA"] * 100

In [12]:
df

,season,team,game_state,minutes,shots,goals,xG,shots_against,goals_against,xGA,...,total_goals,total_goals_against,total_game_time,game_state_percentage,goals_percentage,goals_against_percentage,total_xG,total_xGA,xG_percentage,xGA_percentage
0,2021,Arsenal,Goal diff 0,1472,225,30,26.489456,150,16,13.169800,...,61,48,3579,41.128807,49.180328,33.333333,65.547872,49.562284,40.412381,26.572221
1,2021,Arsenal,Goal diff +1,810,145,17,17.046285,100,8,7.393413,...,61,48,3579,22.632020,27.868852,16.666667,65.547872,49.562284,26.005856,14.917418
2,2021,Arsenal,Goal diff > +1,576,93,10,11.936612,71,8,9.277482,...,61,48,3579,16.093881,16.393443,16.666667,65.547872,49.562284,18.210526,18.718835
3,2021,Arsenal,Goal diff -1,368,82,3,6.066514,47,9,7.577670,...,61,48,3579,10.282202,4.918033,18.750000,65.547872,49.562284,9.255089,15.289187
4,2021,Arsenal,Goal diff < -1,353,42,1,4.009005,58,7,12.143918,...,61,48,3579,9.863090,1.639344,14.583333,65.547872,49.562284,6.116148,24.502338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,2025,Tottenham,Goal diff 0,1766,189,20,20.368882,206,29,25.097431,...,48,57,3679,48.002175,41.666667,50.877193,48.934923,56.126337,41.624429,44.715962
144,2025,Tottenham,Goal diff -1,848,114,12,12.007545,124,12,16.254450,...,48,57,3679,23.049742,25.000000,21.052632,48.934923,56.126337,24.537783,28.960469
145,2025,Tottenham,Goal diff +1,449,46,6,6.156299,66,10,6.495562,...,48,57,3679,12.204403,12.500000,17.543860,48.934923,56.126337,12.580583,11.573109
146,2025,Tottenham,Goal diff < -1,343,52,7,5.915664,43,5,5.390593,...,48,57,3679,9.323186,14.583333,8.771930,48.934923,56.126337,12.088839,9.604391
147,2025,Tottenham,Goal diff > +1,273,35,3,4.486533,26,1,2.888300,...,48,57,3679,7.420495,6.250000,1.754386,48.934923,56.126337,9.168366,5.146069

In [15]:
mapping = {
    "Goal diff > +1": "Winning (2+ goals)",
    "Goal diff +1": "Winning (1 goal)",
    "Goal diff 0": "Drawing",
    "Goal diff -1": "Losing (1 goal)",
    "Goal diff < -1": "Losing (2+ goals)"
}

In [17]:
df["game_state"] = df["game_state"].replace(mapping)

In [18]:
df

,season,team,game_state,minutes,shots,goals,xG,shots_against,goals_against,xGA,...,total_goals,total_goals_against,total_game_time,game_state_percentage,goals_percentage,goals_against_percentage,total_xG,total_xGA,xG_percentage,xGA_percentage
0,2021,Arsenal,Drawing,1472,225,30,26.489456,150,16,13.169800,...,61,48,3579,41.128807,49.180328,33.333333,65.547872,49.562284,40.412381,26.572221
1,2021,Arsenal,Winning (1 goal),810,145,17,17.046285,100,8,7.393413,...,61,48,3579,22.632020,27.868852,16.666667,65.547872,49.562284,26.005856,14.917418
2,2021,Arsenal,Winning (2+ goals),576,93,10,11.936612,71,8,9.277482,...,61,48,3579,16.093881,16.393443,16.666667,65.547872,49.562284,18.210526,18.718835
3,2021,Arsenal,Losing (1 goal),368,82,3,6.066514,47,9,7.577670,...,61,48,3579,10.282202,4.918033,18.750000,65.547872,49.562284,9.255089,15.289187
4,2021,Arsenal,Losing (2+ goals),353,42,1,4.009005,58,7,12.143918,...,61,48,3579,9.863090,1.639344,14.583333,65.547872,49.562284,6.116148,24.502338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,2025,Tottenham,Drawing,1766,189,20,20.368882,206,29,25.097431,...,48,57,3679,48.002175,41.666667,50.877193,48.934923,56.126337,41.624429,44.715962
144,2025,Tottenham,Losing (1 goal),848,114,12,12.007545,124,12,16.254450,...,48,57,3679,23.049742,25.000000,21.052632,48.934923,56.126337,24.537783,28.960469
145,2025,Tottenham,Winning (1 goal),449,46,6,6.156299,66,10,6.495562,...,48,57,3679,12.204403,12.500000,17.543860,48.934923,56.126337,12.580583,11.573109
146,2025,Tottenham,Losing (2+ goals),343,52,7,5.915664,43,5,5.390593,...,48,57,3679,9.323186,14.583333,8.771930,48.934923,56.126337,12.088839,9.604391
147,2025,Tottenham,Winning (2+ goals),273,35,3,4.486533,26,1,2.888300,...,48,57,3679,7.420495,6.250000,1.754386,48.934923,56.126337,9.168366,5.146069

In [21]:
cols_to_keep = ["season", "team", "game_state", "minutes", "total_game_time", "game_state_percentage",
 "goals", "total_goals", "goals_percentage", "xG", "total_xG", "xG_percentage",
 "goals_against", "total_goals_against", "goals_against_percentage", "xGA", "total_xGA", "xGA_percentage"]

In [24]:
df[cols_to_keep].to_csv("data/processed/cleaned_game_state_data.csv", index=False)

In [25]:
df[cols_to_keep].head()

,season,team,game_state,minutes,total_game_time,game_state_percentage,goals,total_goals,goals_percentage,xG,total_xG,xG_percentage,goals_against,total_goals_against,goals_against_percentage,xGA,total_xGA,xGA_percentage
0,2021,Arsenal,Drawing,1472,3579,41.128807,30,61,49.180328,26.489456,65.547872,40.412381,16,48,33.333333,13.169800,49.562284,26.572221
1,2021,Arsenal,Winning (1 goal),810,3579,22.632020,17,61,27.868852,17.046285,65.547872,26.005856,8,48,16.666667,7.393413,49.562284,14.917418
2,2021,Arsenal,Winning (2+ goals),576,3579,16.093881,10,61,16.393443,11.936612,65.547872,18.210526,8,48,16.666667,9.277482,49.562284,18.718835
3,2021,Arsenal,Losing (1 goal),368,3579,10.282202,3,61,4.918033,6.066514,65.547872,9.255089,9,48,18.750000,7.577670,49.562284,15.289187
4,2021,Arsenal,Losing (2+ goals),353,3579,9.863090,1,61,1.639344,4.009005,65.547872,6.116148,7,48,14.583333,12.143918,49.562284,24.502338